### PR TITLE
Support gen24 "BackupMode" value.

### PR DESCRIPTION
**Pull request by schinckel**
This is a boolean value.

### CODE REVIEW

**Comment by farmio** [comment]
👍 
What does "BackupMode" mean?
Could you some test for that value?

**Comment by schinckel** [comment]
From the API docs:
```
# optional field, supported since Fronius Hybrid version 1.3.1-0 
#                 not available on Fronius Non Hybrid
#                 supported on Gen24/Tauro devices
# field is available if configured (false) or active (true)
# if not available, mandatory config is not set. On Gen24 this flag is always available
boolean BackupMode;
```

**Comment by schinckel** [comment]
I'll have to pull the repo down and write up a test then, rather than just work in the GitHub... ;)

**Comment by farmio** [comment]
Sure, but what does it mean when it is true or false? The API docs don't really explain that.

**Comment by schinckel** [comment]
When it's `true`, the battery is backing up the house, when it's `false` it's not.

When it's not present, this is not a hybrid inverter, and when it's `null` battery backup is not configured for the system (I think, although it may just not be present in that case too).

**Comment by farmio** [comment]
> When it's true, the battery is backing up the house

Does that mean that grid power is gone then?

**Comment by schinckel** [comment]
That’s my understanding (and the reason I’d like the value).

It may even work without a battery, using the PVPoint feature, not sure.

**Review by farmio — APPROVED** [review]

**Pull request merged**
