### PR TITLE
Refactored to use asyncio, added support for power flow and storages,…

### PR DESCRIPTION
**Pull request by gbeine**
… harmonized results (result keys are now similar for all APIs)

Merge it, if you like - I use this version for polling my fronius devices with Home Assistant.

### CODE REVIEW

**Comment by nielstron** [comment]
Looks nice, will merge it :)

**Comment by gbeine** [comment]
Thank you - it would be great if you can release it on pypi too.
I use it with Home Assistant as source for my device sensors:
https://github.com/home-assistant/home-assistant/pull/11446

**Comment by nielstron** [comment]
Is already published to pypi ;) Made some adjusting changes for that but package stayed the same overall.                                                                                                                                                                                                                                                                                                                From: notifications@github.comSent: January 4, 2018 10:33To: pyfronius@noreply.github.comReply-to: reply@reply.github.comCc: n.muendler@web.de; state_change@noreply.github.comSubject: Re: [nielstron/pyfronius] Refactored to use asyncio, added support for power flow and storages,… (#1)  Thank you - it would be great if you can release it on pypi too.
I use it with Home Assistant as source for my device sensors:
home-assistant/home-assistant#11446

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by phsdv** [comment]
Very nice! thanks Niels and Gerrit. I was working on a similar asyncio version based on Niels work. Gerrit beat me to it. This version is more complete. I will try it and see if I can get a sensor component in Home Assistant working for this. If any of you have experience with making components, I could use some help in doing so. I have about 70% working already.

**Comment by gbeine** [comment]
@phsdv Hi Paul, I've submitted such a sensor component to Home Assistant already.
That's why I changed Niels' lib to asyncio ;-)

You may find it here: https://github.com/gbeine/home-assistant/tree/fronius

**Comment by phsdv** [comment]
@gbeine thanks! Again, looking much better than what I was working on. 
Besides this do I need to add anything to the sensor section in the configuration file?
>`  - platform: fronius`
>`    host: 192.168.xxx.xxx`
>`    type: inverter`
>`    device: 1`
>`    scope: device`

**Comment by gbeine** [comment]
@phsdv that is all you need for this section.
As the available information provided from the Fronius device depends on its state, I decided to use template sensors and attributes.
`scope` and `device` are optional for inverters (default scope is device where applicable and default device is 1 for inverters)

All data from the inverter is available as attributes, so you may access the PAC via:
```
- platform: template
  sensors:
    electricity_inverter1_power_netto:
      unit_of_measurement: 'W'
      value_template: >-
        {% if states.sensor.fronius_inverter_192178XXXXXX_1.attributes.power_ac is defined %}
          {{ states.sensor.fronius_inverter_192178XXXXXX_1.attributes.power_ac | float | round(2) }}
        {% else %}
          0
        {% endif %}
```
This ensures that the sensor delivers an appropriate value even if the device goes offline (standby or something else).

**Pull request merged**
