### PR TITLE
support v0 of Solar API

### PR DESCRIPTION
**Pull request by trdischat**
Allow alternate URL for inverters/dataloggers that use v0 of the Fronius Solar API.  API version specified as attribute of instance, with 1 as the default.

### CODE REVIEW

**Comment by nielstron** [comment]
It seems to me that you have merely added the option to change the resource URL from ".../v1/..." to ".../.." and the data returned is not different at all - is that correct? Could you add an example for the data returned by an inverter with protocol version v0 (also so that it can be used in a new test case, checking correct functioning of the different API version)?

**Comment by nielstron** [comment]
The full documentation for version v0 can be found [here](https://www.fronius.com/~/downloads/Solar%20Energy/Operating%20Instructions/42%2C0410%2C2011.pdf). I suggest to also include an option to enable automatic api version detection by a call to the described `/solar_api/GetAPIVersion.cgi`

**Comment by trdischat** [comment]
The URL changed in two ways: “v1/“ is removed, and “DeviceId” becomes “DeviceIndex”. As far as I can tell, the data returned is the same, with the exception that v0 flags the json incorrectly with “javascript” as its mime type. But I don’t have a v1 Fronius device to test. As you note, testing the API version is fairly straightforward. I will try to put together something to do that. Thanks.

**Comment by nielstron** [comment]
> But I don’t have a v1 Fronius device to test.

I have a v1 Fronius device, but a v0 device for testing would be nice.

I have already put together my proposal for the change structure in the branch `support_api_version` feel free to check it out.

**Comment by trdischat** [comment]
Just did a quick read-through of the branch. Looks pretty good. One thing to address. In v0, the URL uses “DeviceIndex” not “DeviceId” to refer to the inverter number.  So the current and cumulative URLs need to address this difference.

**Comment by nielstron** [comment]
You're right. In Addition to that small change, I assume that some more small changes would have been conducted from v0 to v1, probably requiring a larger refactoring to allow for version specific input handling.
Feel free to update your personal fork based on my changes to integrate your proposal.

As mentioned, please also provide example data from a v0 device to check if it will actually be handled correctly.

**Comment by trdischat** [comment]
I apologize, but I am not very good at using git for much more than managing version control on my own files.  I barely figured out how create a pull request in the first place.  If you don't mind, could you take a minute to explain to me which branch of your code I should be looking at, and what I should do with github next to help complete this?  Sorry for being such a newb.

**Comment by nielstron** [comment]
Don't worry. I recommend you to get aquainted with `git` (the program on your local machine first). I did not find any satisfying git primer through quick online search, so I'd suggest to skim through a few of them and then google for any specific question you have (almost everything you can do with git is perfectly documented in some StackOverflow question).

The branch I have updated is `api_version_support`, [this](https://github.com/nielstron/pyfronius/tree/api_version_support) is a direct link, however I am not sure if you can copy this branch to your fork of this project via github.
As far as I see there are basically two ways for you to be able to work on that branch
* Delete your fork of my project and create a new fork. This will obviously destroy all changes you have made so far so be sure to save them somewhere
* Work on your local copy
    1) add this repository (https://github.com/nielstron/pyfronius) as a remote to the local clone of your fork 
    2) checkout the branch `api_version_support`
    3) create your own branch based on that branch `git checkout -b myownbranch`
    4) push that branch to your fork and create another pull request

**Comment by trdischat** [comment]
I am really embarrassed to admit this, but I have read your instructions at least a hundred times now, and I still have no idea what I am supposed to do.  I can write python.  I can make commits of my own repos.  But for the life of me, I cannot understand collaborating over GitHub. The whole process of forking, branches, and pull requests is just beyond me.  Sorry.

I did create an output file of the json responses from my v0 datalogger if you are interested.  I have attached it here.  The file contains the responses for each major command URL both when the inverter is active during the day and when it is inactive at night.

[v0_tests.zip](https://github.com/nielstron/pyfronius/files/5254016/v0_tests.zip)

**Comment by nielstron** [comment]
No worries. Thanks a lot for the supplied example file. I'll have a look at including it in the project.

I suggest that you take some time to get yourself aquainted with the deeper usage of git, it comes in very handy for collaborative projects. With a bit of research I found this tutorial, which will guide you through all the required knowledge for the steps I described above: https://www.freecodecamp.org/news/what-is-git-and-how-to-use-it-c341b049ae61/

**Comment by nielstron** [comment]
I checked the contents of the file you supplied. Thanks for the exhaustive overview, even for inactive states. However, in comparison to the requests currently being tested (check `pyfronius/tests/test_structure/solar_api/v1`) a few contents are missing. Does the v0 version of the fronius device not support this?

**Comment by trdischat** [comment]
As far as I can tell from the v0 documentation, it does not support anything beyond standard inverters. So the other commands that you tested in v1 do not exist in v0.

**Comment by nielstron** [comment]
Thanks a lot for your support @trdischat ! Using the supplied data I have implemented support for the fronius API version 0. Feel free to check out the result and test with your own device :)

**Comment by trdischat** [comment]
Niels, I wanted to thank you for adding support for v0 inverters in this library. I am trying to use the Fronius integration in Home Assistant now, and it still does not seem to support the v0 API. It looks like you are a regular contributor to the Fronius integration. Any chance you could add support for v0 in the HA integration, now that it is supported in Pyfronius?

**Comment by nielstron** [comment]
Hi @trdischat ,
I didn't update the component to use the newest version of pyfronius, that's why it's not working yet. Should be a minor change though :)

**Comment by trdischat** [comment]
> I didn't update the component to use the newest version of pyfronius, that's why it's not working yet. Should be a minor change though :)

Thank you!!!!

**Pull request closed without merging**
